name: "🌐 Publicação do Site (GitHub Pages)"

on:
  push:
    branches: ["master"] # Ou "master", dependendo do nome da branch no repo público
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: "📥 Recebendo os arquivos teleportados"
        uses: actions/checkout@v4

      - name: "📦 Empacotando o Site"
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Pega tudo o que estiver na raiz do repo público

      - name: "🚀 Publicando na URL Oficial"
        id: deployment
        uses: actions/deploy-pages@v4
